-- Utilizing the provided tables - Products, Customers, Orders, OrderDetails, and ProductTypes - 
the objective is to formulate SQL queries to retrieve relevant data using Data Query Language (DQL).

-- creating a table for new entity

-- creating a table called "PRODUCTSTYPES"
CREATE TABLE PRODUCTSTYPES (
   PRODUCTSTYPES     INT NOT NULL,
   PRODUCT_NAME    NVARCHAR(40) NOT NULL,
   SUPPLIER_NUMBER INT NOT NULL,
   CATEGORY_CODE   INT NOT NULL,
   QUANTITY        VARCHAR(30),
);
SELECT * FROM PRODUCTS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM PRODUCTSTYPES;

SELECT * FROM CATEGORIES,CUSTOMERS,ORDERS,ORDER_DETAILS,EMPLOYEES,SUPPLIERS,PRODUCTS, PRODUCTSTYPES

SELECT P.PRODUCT_NAME, SUM(OD.Quantity) AS TotalQuantity FROM PRODUCTS P JOIN ORDER_DETAILS OD ON P.PRODUCT_REF  = OD.PRODUCT_REF  GROUP BY P.PRODUCT_NAME;

-- 
SELECT C.CUSTOMER_CODE, COUNT(O.ORDER_NUMBER) AS TotalOrders FROM Customers C JOIN Orders O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE GROUP BY C.CUSTOMER_CODE HAVING COUNT(DISTINCT O.ORDER_DATE) = 7;

SELECT C.CUSTOMER_CODE, COUNT(O.ORDER_NUMBER) AS TotalOrders FROM Customers C JOIN Orders O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE GROUP BY C.CUSTOMER_CODE ORDER BY TotalOrders DESC LIMIT 1;

SELECT P.PRODUCT_NAME, SUM(OD.Quantity) AS TotalQuantity FROM Products P JOIN OrderDetails OD ON P.ProductID = OD.ProductID GROUP BY P.ProductID ORDER BY TotalQuantity DESC;

SELECT DISTINCT C.CUSTOMER_CODE FROM Customers C JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF WHERE P.PRODUCTSTYPES = 'Widget';

SELECT P.PRODUCT_NAME, SUM(OD.Quantity) AS TotalQuantity FROM PRODUCTS P JOIN ORDER_DETAILS OD ON P.PRODUCT_REF = PRODUCT_REF GROUP BY PRODUCT_REF ORDER BY TotalQuantity DESC;